export default {
  EVENT_TYPE_TIME_SPAN_CHANGE: "EVENT_TYPE_TIME_SPAN_CHANGE",
  BOTTOM_TAB_SELECT: "BOTTOM_TAB_SELECT",
  FAVORITE_CHANGED_POPULAR:'Favorite_CHANGED_POPULAR',
  FAVORITE_CHANGED_TRENDING:'FAVORITE_CHANGED_TRENDING',
}